### ISSUE TITLE
Client asking for cluster data will get node IPs

### ISSUE THREAD

**Issue by svenakela** [wojnosystems/redis_cluster_proxy#1]
I deployed the proxy on a Kubernetes cluster to be able to connect to Redis and it works like a charm with `redis-cli`. But when I started a Java client using the `Redisson` library the driver didn't manage to connect to the nodes. 
The Redisson client starts with one node only, asking for the cluster data (`CLUSTER NODES`) during initialization, this will return the list of _real IP addresses_ and the connection to the master nodes will fail as the IPs are not available.
Looking through the code, I can't really come up with a clean solution. The "least dirty" would probably be to map the proxy info to a response that matches the `CLUSTER NODES` command.

``` java
org.redisson.cluster.ClusterConnectionManager - Redis cluster nodes configuration got from localhost/127.0.0.1:8001:
82142f0eae1f09d3179b88eb384b432468841cbd 172.17.0.7:6379@16379 myself,master - 0 1583425973000 1 connected 0-5460
43f26015276d82dd8bb0894edbcfebcfb3bb49f5 172.17.0.8:6379@16379 master - 0 1583425974000 2 connected 5461-10922
9cc4f6eb6354a0e54225f038558326475e39707b 172.17.0.12:6379@16379 slave 43f26015276d82dd8bb0894edbcfebcfb3bb49f5 0 1583425975000 6 connected
50842d38185da2aea1c9da6b7cc01e8b2fe0f4e0 172.17.0.9:6379@16379 master - 0 1583425975836 3 connected 10923-16383
4d051948cac7faf01363a8f87371857c906cb542 172.17.0.11:6379@16379 slave 82142f0eae1f09d3179b88eb384b432468841cbd 0 1583425974820 5 connected
9016442dd63136ae461f9772e2cd2252abd80058 172.17.0.10:6379@16379 slave 50842d38185da2aea1c9da6b7cc01e8b2fe0f4e0 0 1583425973000 4 connected
org.redisson.cluster.ClusterConnectionManager - Can't connect to master: redis://172.17.0.8:6379 with slot ranges: [[5461-10922]]
org.redisson.cluster.ClusterConnectionManager - Can't connect to master: redis://172.17.0.9:6379 with slot ranges: [[10923-16383]]
org.redisson.cluster.ClusterConnectionManager - Can't connect to master: redis://172.17.0.7:6379 with slot ranges: [[0-5460]]
```

**Comment by wojnosystems** [comment]
Hey Sven. Thanks for your interest.

Your issue is totally familiar. It's pretty much why I wrote this proxy. I did my testing against the Jedis client, which does a query up-front using the `CLUSTER slots` command and this is done when the client connects. Since your client is querying through CLUSTER NODES, we need to add in a catch & mutate for that command.

That's essentially how this proxy works, it sniffs all of the traffic and when it sees something it recognizes, it swaps it out with the proxied host.

Best place is to add a new if statement to https://github.com/wojnosystems/redis_cluster_proxy/blob/af83bd0716ea722bc7d4b6f235cc3420fdc75f22/pkg/proxy/redis.go#L239

This function intercepts messages from the client (but this could also be from the server). It gives you a chance to query the internal state of the proxy. See the  mutateClusterSlotsCommand https://github.com/wojnosystems/redis_cluster_proxy/blob/af83bd0716ea722bc7d4b6f235cc3420fdc75f22/pkg/proxy/redis.go#L286

Since I'm not sure what your client is sending, it'll be hard for me to help you out on this. You may wish to create a test harness for this.

For the code, you'll create a new interception method/function. The intercepter code needs to know which command is being sent by the client. The, you can switch against the one you want e.g.: "CLUSTER NODES" and then read from the client's socket until the command has terminated. COmmands in Redis can be pipelined, so it's important that you do this to avoid errors with future commands that are sent.

Then, create a fake CLUSTER NODES response and return it from your intercepter function. The library will handle the rest. Lemme post my harness for you as a guide.

**Comment by wojnosystems** [comment]
Here's what I used to test the proxy: https://github.com/wojnosystems/redis_cluster_proxy_harness. It uses Jedis, of course. But you can swap out with your library.

**Comment by wojnosystems** [comment]
I updated the repo to add in a debugging option that's now enabled by default in the docker-compose file. You'll be able to see the commands that the client sends as well as the server responses.

**Comment by wojnosystems** [comment]
I've added support for CLUSTER NODES. I haven't tested it beyond using CLUSTER NODES in redis-cli, and it seems to work.
Give it a shot in your test harness.

**Comment by swtrustly** [comment]
Sweet! I was looking at the slots mutation yesterday, you were faster! 
I will test your code change ASAP.

**Comment by wojnosystems** [comment]
Cool. Let me know how it goes. The docker version 1.0.3 has these changes.

**Comment by svenakela** [comment]
Works as expected. :+1: 
I've made the project into a Docker hub image by a fork of yours. You can run a docker container with
`docker run --name redis-proxy -d -e "LISTEN_ADDR=:8000" -e "CLUSTER_ADDR=cluster:7000" svenakela/wojno-redis-proxy:latest`
