### ISSUE TITLE
support for RESP3 or RESP3 capable clients

### ISSUE THREAD

**Issue by kilx** [wojnosystems/redis_cluster_proxy#2]
Thanks, this still looks like the only workable solution to have a Redis cluster behind NAT and be accessible from both outside and inside. E.g. Windows and MacOS docker environments where the internal network is not accessible to the host and there's no host type network available either on these platforms.

However it doesn't work with Redis 6 nor even Redis 5 with a Redis 6 client, it seems. Any plans on supporting RESP3? I understand this mostly means adding new field types.

**Comment by wojnosystems** [comment]
Hey kilx,

Sadly, no. I have no plans to support Redis 6 at this time. This was something I needed for Redis 5 and I no longer have a use case for Redis 6. Feel free to fork and add to it. If you open a PR and demonstrate it works with tests, I'd probably merge it in.

If this is for a business entity, I'd be open to compensation for adding the fields so that it could be used with RESP3. This looks like a significant re-write of the protocol, so this would take some time to complete.

Thanks for your interest in the project. Glad you got some utility out of it!
